#ifdef HIENA_MEMFUNC

HIENA_MEMFUNC( /*const*/,	/*volatile*/,	,	/*noexcept*/)
HIENA_MEMFUNC( const,		/*volatile*/,	,	/*noexcept*/)
HIENA_MEMFUNC( /*const*/,	volatile,		,	/*noexcept*/)
HIENA_MEMFUNC( const,		volatile,		,	/*noexcept*/)
HIENA_MEMFUNC( /*const*/,	/*volatile*/,	&,	/*noexcept*/)
HIENA_MEMFUNC( const,		/*volatile*/,	&,	/*noexcept*/)
HIENA_MEMFUNC( /*const*/,	volatile,		&,	/*noexcept*/)
HIENA_MEMFUNC( const,		volatile,		&,	/*noexcept*/)
HIENA_MEMFUNC( /*const*/,	/*volatile*/,	&&,	/*noexcept*/)
HIENA_MEMFUNC( const,		/*volatile*/,	&&,	/*noexcept*/)
HIENA_MEMFUNC( /*const*/,	volatile,		&&,	/*noexcept*/)
HIENA_MEMFUNC( const,		volatile,		&&,	/*noexcept*/)
HIENA_MEMFUNC( /*const*/,	/*volatile*/,	,	noexcept)
HIENA_MEMFUNC( const,		/*volatile*/,	,	noexcept)
HIENA_MEMFUNC( /*const*/,	volatile,		,	noexcept)
HIENA_MEMFUNC( const,		volatile,		,	noexcept)
HIENA_MEMFUNC( /*const*/,	/*volatile*/,	&,	noexcept)
HIENA_MEMFUNC( const,		/*volatile*/,	&,	noexcept)
HIENA_MEMFUNC( /*const*/,	volatile,		&,	noexcept)
HIENA_MEMFUNC( const,		volatile,		&,	noexcept)
HIENA_MEMFUNC( /*const*/,	/*volatile*/,	&&,	noexcept)
HIENA_MEMFUNC( const,		/*volatile*/,	&&,	noexcept)
HIENA_MEMFUNC( /*const*/,	volatile,		&&,	noexcept)
HIENA_MEMFUNC( const,		volatile,		&&,	noexcept)

#endif

#ifdef HIENA_MEMFUNC_VARIADIC

HIENA_MEMFUNC_VARIADIC( /*const*/,	/*volatile*/,	,	/*noexcept*/)
HIENA_MEMFUNC_VARIADIC( const,		/*volatile*/,	,	/*noexcept*/)
HIENA_MEMFUNC_VARIADIC( /*const*/,	volatile,		,	/*noexcept*/)
HIENA_MEMFUNC_VARIADIC( const,		volatile,		,	/*noexcept*/)
HIENA_MEMFUNC_VARIADIC( /*const*/,	/*volatile*/,	&,	/*noexcept*/)
HIENA_MEMFUNC_VARIADIC( const,		/*volatile*/,	&,	/*noexcept*/)
HIENA_MEMFUNC_VARIADIC( /*const*/,	volatile,		&,	/*noexcept*/)
HIENA_MEMFUNC_VARIADIC( const,		volatile,		&,	/*noexcept*/)
HIENA_MEMFUNC_VARIADIC( /*const*/,	/*volatile*/,	&&,	/*noexcept*/)
HIENA_MEMFUNC_VARIADIC( const,		/*volatile*/,	&&,	/*noexcept*/)
HIENA_MEMFUNC_VARIADIC( /*const*/,	volatile,		&&,	/*noexcept*/)
HIENA_MEMFUNC_VARIADIC( const,		volatile,		&&,	/*noexcept*/)
HIENA_MEMFUNC_VARIADIC( /*const*/,	/*volatile*/,	,	noexcept)
HIENA_MEMFUNC_VARIADIC( const,		/*volatile*/,	,	noexcept)
HIENA_MEMFUNC_VARIADIC( /*const*/,	volatile,		,	noexcept)
HIENA_MEMFUNC_VARIADIC( const,		volatile,		,	noexcept)
HIENA_MEMFUNC_VARIADIC( /*const*/,	/*volatile*/,	&,	noexcept)
HIENA_MEMFUNC_VARIADIC( const,		/*volatile*/,	&,	noexcept)
HIENA_MEMFUNC_VARIADIC( /*const*/,	volatile,		&,	noexcept)
HIENA_MEMFUNC_VARIADIC( const,		volatile,		&,	noexcept)
HIENA_MEMFUNC_VARIADIC( /*const*/,	/*volatile*/,	&&,	noexcept)
HIENA_MEMFUNC_VARIADIC( const,		/*volatile*/,	&&,	noexcept)
HIENA_MEMFUNC_VARIADIC( /*const*/,	volatile,		&&,	noexcept)
HIENA_MEMFUNC_VARIADIC( const,		volatile,		&&,	noexcept)

#endif