#pragma once

#define HIENA_PP_PACK(...) (__VA_ARGS__)
#define HIENA_PP_UNPACK(...) __VA_ARGS__

#define HIENA_PP_CONCAT_IMPL2(A, B) A ## B
#define HIENA_PP_CONCAT_IMPL(A, B) HIENA_PP_CONCAT_IMPL2(A, B)
#define HIENA_PP_CONCAT(A, B) HIENA_PP_CONCAT_IMPL(A, B)

// Deferral macros to trigger more expansions
#define HIENA_PP_EMPTY()
#define HIENA_PP_DEFER(id) id HIENA_PP_EMPTY()
#define HIENA_PP_OBSTRUCT(...) __VA_ARGS__ HIENA_PP_DEFER(HIENA_PP_EMPTY)()

#define HIENA_PP_FIRST(F, ...) F
#define HIENA_PP_TAIL(F, ...) (__VA_ARGS__)
#define HIENA_PP_PUSH_BACK(F, ...) __VA_ARGS__, F
#define HIENA_PP_PUSH_FRONT(F, ...) F, __VA_ARGS__

// HIENA_PP_NUM_ARGS(...) Size of the variadic pack (Up to 64)
#define HIENA_PP_NUM_ARGS2(X,X64,X63,X62,X61,X60,X59,X58,X57,X56,X55,X54,X53,X52,X51,X50,X49,X48,X47,X46,X45,X44,X43,X42,X41,X40,X39,X38,X37,X36,X35,X34,X33,X32,X31,X30,X29,X28,X27,X26,X25,X24,X23,X22,X21,X20,X19,X18,X17,X16,X15,X14,X13,X12,X11,X10,X9,X8,X7,X6,X5,X4,X3,X2,X1,N,...) N
#define HIENA_PP_NUM_ARGS(...) HIENA_PP_NUM_ARGS2(0, __VA_ARGS__ ,64,63,62,61,60,59,58,57,56,55,54,53,52,51,50,49,48,47,46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0)

// Zips 2 packs of same size. SET is the separator
// Example:
// HIENA_PP_ZIP((a,b,c),(,),(1,2,3) produces a1, a2, a3
#define HIENA_PP_ZIP_IMPL2(N, M, PACK1, SEP, PACK2)	HIENA_PP_ZIP ## N ##_## M(PACK1, SEP, PACK2)
#define HIENA_PP_ZIP_IMPL(N, M, PACK1, SEP, PACK2)	HIENA_PP_ZIP_IMPL2(N, M, PACK1, SEP, PACK2)
#define HIENA_PP_ZIP(PACK1, SEP, PACK2)				HIENA_PP_ZIP_IMPL(HIENA_PP_NUM_ARGS(HIENA_PP_UNPACK PACK1), HIENA_PP_NUM_ARGS(HIENA_PP_UNPACK PACK2), PACK1, SEP, PACK2)

#define HIENA_PP_ZIP_FIRST(PACK1, PACK2)			HIENA_PP_FIRST PACK1 HIENA_PP_FIRST PACK2

#define HIENA_PP_ZIP32_32(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP31_31(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP31_31(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP30_30(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP30_30(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP29_29(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP29_29(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP28_28(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP28_28(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP27_27(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP27_27(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP26_26(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP26_26(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP25_25(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP25_25(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP24_24(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP24_24(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP23_23(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP23_23(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP22_22(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP22_22(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP21_21(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP21_21(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP20_20(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP20_20(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP19_19(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP19_19(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP18_18(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP18_18(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP17_17(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP17_17(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP16_16(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP16_16(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP15_15(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP15_15(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP14_14(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP14_14(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP13_13(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP13_13(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP12_12(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP12_12(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP11_11(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP11_11(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP10_10(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP10_10(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP9_9(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP9_9(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP8_8(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP8_8(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP7_7(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP7_7(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP6_6(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP6_6(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP5_5(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP5_5(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP4_4(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP4_4(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP3_3(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP3_3(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP2_2(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP2_2(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2) HIENA_PP_UNPACK SEP HIENA_PP_ZIP1_1(HIENA_PP_TAIL PACK1, SEP, HIENA_PP_TAIL PACK2)
#define HIENA_PP_ZIP1_1(PACK1, SEP, PACK2) HIENA_PP_ZIP_FIRST(PACK1, PACK2)

// Generates n identifiers (max 32)
#define HIENA_PP_APPLY(M, ...) M(__VA_ARGS__)
#define HIENA_PP_IDS(ID, N) HIENA_PP_APPLY(HIENA_PP_ID_##N, ID)
#define HIENA_PP_NAMED_FUNC_ARGS(TYPESPACK, ARGPREFIX) HIENA_PP_PACK(HIENA_PP_DEFER(HIENA_PP_IDS)(ARGPREFIX, HIENA_PP_NUM_ARGS(HIENA_PP_UNPACK TYPESPACK)))

#define HIENA_PP_ID_1(ID) ID##1
#define HIENA_PP_ID_2(ID) HIENA_PP_ID_1(ID), ID##2
#define HIENA_PP_ID_3(ID) HIENA_PP_ID_2(ID), ID##3
#define HIENA_PP_ID_4(ID) HIENA_PP_ID_3(ID), ID##4
#define HIENA_PP_ID_5(ID) HIENA_PP_ID_4(ID), ID##5
#define HIENA_PP_ID_6(ID) HIENA_PP_ID_5(ID), ID##6
#define HIENA_PP_ID_7(ID) HIENA_PP_ID_6(ID), ID##7
#define HIENA_PP_ID_8(ID) HIENA_PP_ID_7(ID), ID##8
#define HIENA_PP_ID_9(ID) HIENA_PP_ID_8(ID), ID##9
#define HIENA_PP_ID_10(ID) HIENA_PP_ID_9(ID), ID##10
#define HIENA_PP_ID_11(ID) HIENA_PP_ID_10(ID), ID##11
#define HIENA_PP_ID_12(ID) HIENA_PP_ID_11(ID), ID##12
#define HIENA_PP_ID_13(ID) HIENA_PP_ID_12(ID), ID##13
#define HIENA_PP_ID_14(ID) HIENA_PP_ID_13(ID), ID##14
#define HIENA_PP_ID_15(ID) HIENA_PP_ID_14(ID), ID##15
#define HIENA_PP_ID_16(ID) HIENA_PP_ID_15(ID), ID##16
#define HIENA_PP_ID_17(ID) HIENA_PP_ID_16(ID), ID##17
#define HIENA_PP_ID_18(ID) HIENA_PP_ID_17(ID), ID##18
#define HIENA_PP_ID_19(ID) HIENA_PP_ID_18(ID), ID##19
#define HIENA_PP_ID_20(ID) HIENA_PP_ID_19(ID), ID##20
#define HIENA_PP_ID_21(ID) HIENA_PP_ID_20(ID), ID##21
#define HIENA_PP_ID_22(ID) HIENA_PP_ID_21(ID), ID##22
#define HIENA_PP_ID_23(ID) HIENA_PP_ID_22(ID), ID##23
#define HIENA_PP_ID_24(ID) HIENA_PP_ID_23(ID), ID##24
#define HIENA_PP_ID_25(ID) HIENA_PP_ID_24(ID), ID##25
#define HIENA_PP_ID_26(ID) HIENA_PP_ID_25(ID), ID##26
#define HIENA_PP_ID_27(ID) HIENA_PP_ID_26(ID), ID##27
#define HIENA_PP_ID_28(ID) HIENA_PP_ID_27(ID), ID##28
#define HIENA_PP_ID_29(ID) HIENA_PP_ID_28(ID), ID##29
#define HIENA_PP_ID_30(ID) HIENA_PP_ID_29(ID), ID##30
#define HIENA_PP_ID_31(ID) HIENA_PP_ID_30(ID), ID##31
#define HIENA_PP_ID_32(ID) HIENA_PP_ID_31(ID), ID##32