#pragma once

#define HIENA_PP_PACK(...) (__VA_ARGS__)
#define HIENA_PP_UNPACK(...) __VA_ARGS__

#define HIENA_PP_APPLY(M, ...) M(__VA_ARGS__)
#define HIENA_PP_IDS(ID, N) HIENA_PP_APPLY(HIENA_PP_ID_##N, ID)

#define HIENA_PP_ID_1(ID) ID##1
#define HIENA_PP_ID_2(ID) HIENA_PP_ID_1(ID), ID##2
#define HIENA_PP_ID_3(ID) HIENA_PP_ID_2(ID), ID##3
#define HIENA_PP_ID_4(ID) HIENA_PP_ID_3(ID), ID##4
#define HIENA_PP_ID_5(ID) HIENA_PP_ID_4(ID), ID##5
#define HIENA_PP_ID_6(ID) HIENA_PP_ID_5(ID), ID##6
#define HIENA_PP_ID_7(ID) HIENA_PP_ID_6(ID), ID##7
#define HIENA_PP_ID_8(ID) HIENA_PP_ID_7(ID), ID##8
#define HIENA_PP_ID_9(ID) HIENA_PP_ID_8(ID), ID##9
#define HIENA_PP_ID_10(ID) HIENA_PP_ID_9(ID), ID##10
#define HIENA_PP_ID_11(ID) HIENA_PP_ID_10(ID), ID##11
#define HIENA_PP_ID_12(ID) HIENA_PP_ID_11(ID), ID##12
#define HIENA_PP_ID_13(ID) HIENA_PP_ID_12(ID), ID##13
#define HIENA_PP_ID_14(ID) HIENA_PP_ID_13(ID), ID##14
#define HIENA_PP_ID_15(ID) HIENA_PP_ID_14(ID), ID##15
#define HIENA_PP_ID_16(ID) HIENA_PP_ID_15(ID), ID##16
#define HIENA_PP_ID_17(ID) HIENA_PP_ID_16(ID), ID##17
#define HIENA_PP_ID_18(ID) HIENA_PP_ID_17(ID), ID##18
#define HIENA_PP_ID_19(ID) HIENA_PP_ID_18(ID), ID##19
#define HIENA_PP_ID_20(ID) HIENA_PP_ID_19(ID), ID##20
#define HIENA_PP_ID_21(ID) HIENA_PP_ID_20(ID), ID##21
#define HIENA_PP_ID_22(ID) HIENA_PP_ID_21(ID), ID##22
#define HIENA_PP_ID_23(ID) HIENA_PP_ID_22(ID), ID##23
#define HIENA_PP_ID_24(ID) HIENA_PP_ID_23(ID), ID##24
#define HIENA_PP_ID_25(ID) HIENA_PP_ID_24(ID), ID##25
#define HIENA_PP_ID_26(ID) HIENA_PP_ID_25(ID), ID##26
#define HIENA_PP_ID_27(ID) HIENA_PP_ID_26(ID), ID##27
#define HIENA_PP_ID_28(ID) HIENA_PP_ID_27(ID), ID##28
#define HIENA_PP_ID_29(ID) HIENA_PP_ID_28(ID), ID##29
#define HIENA_PP_ID_30(ID) HIENA_PP_ID_29(ID), ID##30
#define HIENA_PP_ID_31(ID) HIENA_PP_ID_30(ID), ID##31
#define HIENA_PP_ID_32(ID) HIENA_PP_ID_31(ID), ID##32